// ----------------------------------------------------------------------------
// Kinisi motr controller commands.
// This file is auto generated by the commands generator from JSON file.
// Do not edit this file manually.
// Timestamp: 2026-07-30 22:56:00
// Version: 1.4.0
// ----------------------------------------------------------------------------

#include "kinisi.h"
#include "Wire.h"

// Constructor
KinisiController::KinisiController(int address)
{
    this->address = address;
}

// Begin
void KinisiController::begin()
{
    Wire.begin();
}

// INITIALIZE_MOTOR: This command initializes a motor and prepares it for use. Ignored if the motor is currently owned by an active platform (one of its wheels), so platform wheels are not reconfigured out from under the platform.
void KinisiController::initialize_motor(uint8_t motor_index, bool is_reversed)
{
    unsigned char cmd[] = {INITIALIZE_MOTOR, motor_index, is_reversed};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// SET_MOTOR_SPEED: This command sets the speed of the specified motor in PWM. Ignored if the motor is currently owned by an active platform (one of its wheels); use the platform velocity commands to drive platform wheels.
void KinisiController::set_motor_speed(uint8_t motor_index, double pwm)
{
    unsigned char cmd[] = {SET_MOTOR_SPEED, motor_index, pwm};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// STOP_MOTOR: Coasts the motor to a stop: both H-bridge outputs are driven low, leaving the motor terminals open (high impedance) so it free-wheels and spins down gradually under its own friction. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to stop a platform, use STOP_PLATFORM_CONTROLLER, COAST_PLATFORM or BRAKE_PLATFORM instead. Use STOP_MOTOR for a soft, low-stress stop; use BRAKE_MOTOR when you need the motor to hold position and stop quickly.
void KinisiController::stop_motor(uint8_t motor_index)
{
    unsigned char cmd[] = {STOP_MOTOR, motor_index};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// BRAKE_MOTOR: Actively brakes the motor (short brake): both H-bridge outputs are driven high, shorting the motor terminals together so the motor's own back-EMF resists rotation and it stops quickly and holds position. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to brake a platform, use BRAKE_PLATFORM (or STOP_PLATFORM_CONTROLLER / COAST_PLATFORM) instead. Use BRAKE_MOTOR for a fast, holding stop; use STOP_MOTOR to let the motor coast freely instead.
void KinisiController::brake_motor(uint8_t motor_index)
{
    unsigned char cmd[] = {BRAKE_MOTOR, motor_index};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// INITIALIZE_MOTOR_CONTROLLER: This command sets the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels), so it cannot create a competing controller on a platform wheel.
void KinisiController::initialize_motor_controller(uint8_t motor_index, bool is_reversed, uint8_t encoder_index, bool is_encoder_reversed, double encoder_resolution, double kp, double ki, double kd, double integral_limit)
{
    unsigned char cmd[] = {INITIALIZE_MOTOR_CONTROLLER, motor_index, is_reversed, encoder_index, is_encoder_reversed, encoder_resolution, kp, ki, kd, integral_limit};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// SET_MOTOR_TARGET_SPEED: This command sets the target speed for the specified motor in radians. Ignored if the motor is currently owned by an active platform (one of its wheels); use SET_PLATFORM_TARGET_VELOCITY to drive platform wheels.
void KinisiController::set_motor_target_speed(uint8_t motor_index, double speed)
{
    unsigned char cmd[] = {SET_MOTOR_TARGET_SPEED, motor_index, speed};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// RESET_MOTOR_CONTROLLER: This command resets the closed-loop controller for the specified motor: it clears the accumulated PID state (integrator windup, derivative history and internal output) and re-zeros the target speed, while keeping the controller running with its existing tuning (kp/ki/kd). Use it to recover from integrator windup or to bring a motor cleanly to a stop without deleting and re-initializing the controller. No effect if no controller is running for that motor, and ignored if the motor is currently owned by an active platform (one of its wheels).
void KinisiController::reset_motor_controller(uint8_t motor_index)
{
    unsigned char cmd[] = {RESET_MOTOR_CONTROLLER, motor_index};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_MOTOR_CONTROLLER_STATE: This command gets the state of the controller for the specified motor.
object KinisiController::get_motor_controller_state(uint8_t motor_index)
{
    unsigned char cmd[] = {GET_MOTOR_CONTROLLER_STATE, motor_index};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(object)] = {0};
    ReceiveResponse(this->address, response, sizeof(object));
    return *(object*)response;
}

// DELETE_MOTOR_CONTROLLER: This command deletes the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels); use STOP_PLATFORM_CONTROLLER to stop the platform controller instead.
void KinisiController::delete_motor_controller(uint8_t motor_index)
{
    unsigned char cmd[] = {DELETE_MOTOR_CONTROLLER, motor_index};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// SET_CONTROLLER_FREQUENCY: This command sets the global update frequency (in Hz) of the closed-loop motor controller task. All motor controllers share a single control loop, so this frequency is global and affects every currently running controller as well as any created afterwards; the PID sampling time is updated to match. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 10 Hz (100 ms) at start-up.
void KinisiController::set_controller_frequency(uint16_t frequency)
{
    unsigned char cmd[] = {SET_CONTROLLER_FREQUENCY, frequency};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_CONTROLLER_FREQUENCY: This command retrieves the current global update frequency (in Hz) of the closed-loop motor controller task.
uint16_t KinisiController::get_controller_frequency()
{
    unsigned char cmd[] = {GET_CONTROLLER_FREQUENCY};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(uint16_t)] = {0};
    ReceiveResponse(this->address, response, sizeof(uint16_t));
    return *(uint16_t*)response;
}

// INITIALIZE_ENCODER: This command initializes an encoder and prepares it for use.
void KinisiController::initialize_encoder(uint8_t encoder_index, double encoder_resolution, bool is_reversed)
{
    unsigned char cmd[] = {INITIALIZE_ENCODER, encoder_index, encoder_resolution, is_reversed};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_ENCODER_VALUE: This command retrieves the current value of the encoder.
uint16_t KinisiController::get_encoder_value(uint8_t encoder_index)
{
    unsigned char cmd[] = {GET_ENCODER_VALUE, encoder_index};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(uint16_t)] = {0};
    ReceiveResponse(this->address, response, sizeof(uint16_t));
    return *(uint16_t*)response;
}

// START_ENCODER_ODOMETRY: This command starts the odometry calculation for the specified encoder.
void KinisiController::start_encoder_odometry(uint8_t encoder_index)
{
    unsigned char cmd[] = {START_ENCODER_ODOMETRY, encoder_index};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// RESET_ENCODER_ODOMETRY: This command resets the odometry calculation for the specified encoder.
void KinisiController::reset_encoder_odometry(uint8_t encoder_index)
{
    unsigned char cmd[] = {RESET_ENCODER_ODOMETRY, encoder_index};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// STOP_ENCODER_ODOMETRY: This command stops the odometry calculation for the specified encoder.
void KinisiController::stop_encoder_odometry(uint8_t encoder_index)
{
    unsigned char cmd[] = {STOP_ENCODER_ODOMETRY, encoder_index};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_ENCODER_ODOMETRY: This command retrieves the odometry of the specified encoder.
double KinisiController::get_encoder_odometry(uint8_t encoder_index)
{
    unsigned char cmd[] = {GET_ENCODER_ODOMETRY, encoder_index};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(double)] = {0};
    ReceiveResponse(this->address, response, sizeof(double));
    return *(double*)response;
}

// SET_ODOMETRY_FREQUENCY: This command sets the global update frequency (in Hz) of the odometry task. A single odometry task integrates all encoder and platform odometry, so this frequency is global. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 20 Hz (50 ms) at start-up.
void KinisiController::set_odometry_frequency(uint16_t frequency)
{
    unsigned char cmd[] = {SET_ODOMETRY_FREQUENCY, frequency};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_ODOMETRY_FREQUENCY: This command retrieves the current global update frequency (in Hz) of the odometry task.
uint16_t KinisiController::get_odometry_frequency()
{
    unsigned char cmd[] = {GET_ODOMETRY_FREQUENCY};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(uint16_t)] = {0};
    ReceiveResponse(this->address, response, sizeof(uint16_t));
    return *(uint16_t*)response;
}

// INITIALIZE_GPIO_PIN: This command initializes a digital pin and prepares it for use.
void KinisiController::initialize_gpio_pin(uint8_t pin_number, uint8_t mode)
{
    unsigned char cmd[] = {INITIALIZE_GPIO_PIN, pin_number, mode};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// SET_GPIO_PIN_STATE: This command sets the specified pin to a state.
void KinisiController::set_gpio_pin_state(uint8_t pin_number, uint8_t state)
{
    unsigned char cmd[] = {SET_GPIO_PIN_STATE, pin_number, state};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_GPIO_PIN_STATE: This command gets the state of the specified pin.
uint8_t KinisiController::get_gpio_pin_state(uint8_t pin_number)
{
    unsigned char cmd[] = {GET_GPIO_PIN_STATE, pin_number};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(uint8_t)] = {0};
    ReceiveResponse(this->address, response, sizeof(uint8_t));
    return *(uint8_t*)response;
}

// TOGGLE_GPIO_PIN_STATE: This command toggles the specified pin.
void KinisiController::toggle_gpio_pin_state(uint8_t pin_number)
{
    unsigned char cmd[] = {TOGGLE_GPIO_PIN_STATE, pin_number};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// SET_STATUS_LED_STATE: This command sets the status LED to a state.
void KinisiController::set_status_led_state(uint8_t state)
{
    unsigned char cmd[] = {SET_STATUS_LED_STATE, state};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// TOGGLE_STATUS_LED_STATE: This command toggles the status LED.
void KinisiController::toggle_status_led_state()
{
    unsigned char cmd[] = {TOGGLE_STATUS_LED_STATE};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// INITIALIZE_MECANUM_PLATFORM: This command initializes a mecanum (4-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1, 2 and 3 (one per wheel), which correspond to the is_reversed_0..3 and is_encoder_reversed_0..3 parameters. All four motor slots are occupied by this platform.
void KinisiController::initialize_mecanum_platform(bool is_reversed_0, bool is_reversed_1, bool is_reversed_2, bool is_reversed_3, bool is_encoder_reversed_0, bool is_encoder_reversed_1, bool is_encoder_reversed_2, bool is_encoder_reversed_3, double length, double width, double wheels_diameter, double encoder_resolution)
{
    unsigned char cmd[] = {INITIALIZE_MECANUM_PLATFORM, is_reversed_0, is_reversed_1, is_reversed_2, is_reversed_3, is_encoder_reversed_0, is_encoder_reversed_1, is_encoder_reversed_2, is_encoder_reversed_3, length, width, wheels_diameter, encoder_resolution};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// INITIALIZE_OMNI_PLATFORM: This command initializes an omni (3-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1 and 2 (one per wheel), which correspond to the is_reversed_0..2 and is_encoder_reversed_0..2 parameters. Motor index 3 is not used by this platform and stays free for other purposes.
void KinisiController::initialize_omni_platform(bool is_reversed_0, bool is_reversed_1, bool is_reversed_2, bool is_encoder_reversed_0, bool is_encoder_reversed_1, bool is_encoder_reversed_2, double wheels_diameter, double robot_radius, double encoder_resolution)
{
    unsigned char cmd[] = {INITIALIZE_OMNI_PLATFORM, is_reversed_0, is_reversed_1, is_reversed_2, is_encoder_reversed_0, is_encoder_reversed_1, is_encoder_reversed_2, wheels_diameter, robot_radius, encoder_resolution};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// INITIALIZE_DIFFERENTIAL_PLATFORM: This command initializes a differential (2-wheel) platform and prepares it for use. It uses motor and encoder index 0 for the left wheel and index 1 for the right wheel, which correspond to the is_reversed_0/1 and is_encoder_reversed_0/1 parameters. Motor indices 2 and 3 are not used by this platform and stay free for other purposes.
void KinisiController::initialize_differential_platform(bool is_reversed_0, bool is_reversed_1, bool is_encoder_reversed_0, bool is_encoder_reversed_1, double wheel_diameter, double wheel_base, double encoder_resolution)
{
    unsigned char cmd[] = {INITIALIZE_DIFFERENTIAL_PLATFORM, is_reversed_0, is_reversed_1, is_encoder_reversed_0, is_encoder_reversed_1, wheel_diameter, wheel_base, encoder_resolution};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// SET_PLATFORM_VELOCITY: This command sets the velocity for the platform in PWM.
void KinisiController::set_platform_velocity(double x, double y, double t)
{
    unsigned char cmd[] = {SET_PLATFORM_VELOCITY, x, y, t};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// START_PLATFORM_CONTROLLER: This command sets the controller for the platform.
void KinisiController::start_platform_controller(double kp, double ki, double kd, double integral_limit)
{
    unsigned char cmd[] = {START_PLATFORM_CONTROLLER, kp, ki, kd, integral_limit};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// SET_PLATFORM_TARGET_VELOCITY: This command set the target velocity for the platform in meters per second.
void KinisiController::set_platform_target_velocity(double x, double y, double t)
{
    unsigned char cmd[] = {SET_PLATFORM_TARGET_VELOCITY, x, y, t};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_PLATFORM_CURRENT_VELOCITY: This command gets the current velocity of the platform in meters per second.
object KinisiController::get_platform_current_velocity()
{
    unsigned char cmd[] = {GET_PLATFORM_CURRENT_VELOCITY};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(object)] = {0};
    ReceiveResponse(this->address, response, sizeof(object));
    return *(object*)response;
}

// STOP_PLATFORM_CONTROLLER: This command stops the controller for the platform.
void KinisiController::stop_platform_controller()
{
    unsigned char cmd[] = {STOP_PLATFORM_CONTROLLER};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// START_PLATFORM_ODOMETRY: This command starts the odometry calculation for the platform.
void KinisiController::start_platform_odometry()
{
    unsigned char cmd[] = {START_PLATFORM_ODOMETRY};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// RESET_PLATFORM_ODOMETRY: This command resets the odometry calculation for the platform.
void KinisiController::reset_platform_odometry()
{
    unsigned char cmd[] = {RESET_PLATFORM_ODOMETRY};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// STOP_PLATFORM_ODOMETRY: This command stops the odometry calculation for the platform.
void KinisiController::stop_platform_odometry()
{
    unsigned char cmd[] = {STOP_PLATFORM_ODOMETRY};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// GET_PLATFORM_ODOMETRY: This command retrieves the odometry of the platform in meters and radians.
object KinisiController::get_platform_odometry()
{
    unsigned char cmd[] = {GET_PLATFORM_ODOMETRY};
    SendMessage(this->address, cmd, sizeof(cmd));
    uint8_t response[sizeof(object)] = {0};
    ReceiveResponse(this->address, response, sizeof(object));
    return *(object*)response;
}

// BRAKE_PLATFORM: This command actively brakes all of this platform's wheel motors (short brake) so they resist motion and hold position, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors resist motion until a new command is issued.
void KinisiController::brake_platform()
{
    unsigned char cmd[] = {BRAKE_PLATFORM};
    SendMessage(this->address, cmd, sizeof(cmd));
}

// COAST_PLATFORM: This command lets all of this platform's wheel motors coast freely (high impedance) so they spin down without resistance, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors spin down without resistance.
void KinisiController::coast_platform()
{
    unsigned char cmd[] = {COAST_PLATFORM};
    SendMessage(this->address, cmd, sizeof(cmd));
}

