// ----------------------------------------------------------------------------
// Kinisi motr controller commands.
// This file is auto generated by the commands generator from JSON file.
// Do not edit this file manually.
// Timestamp: 2023-10-19 23:59:00
// Version: 1.0.1
// ----------------------------------------------------------------------------

#include "kinisi.h"
#include "Wire.h"

// Constructor
KinisiController::KinisiController(int address)
{
    this->address = address;
}

// Begin
void KinisiController::begin()
{
    Wire.begin();
}

// INITIALIZE_MOTOR: This command initializes a motor and prepares it for use.
void KinisiController::initialize_motor(uint8_t motor_index)
{
    unsigned char cmd[] = {INITIALIZE_MOTOR, motor_index};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// SET_MOTOR_SPEED: This command sets the speed of the specified motor.
void KinisiController::set_motor_speed(uint8_t motor_index, uint8_t direction, uint16_t speed)
{
    unsigned char cmd[] = {SET_MOTOR_SPEED, motor_index, direction, speed};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// INITIALIZE_MOTOR_CONTROLLER: This command sets the controller for the specified motor.
void KinisiController::initialize_motor_controller(uint8_t motor_index, double kp, double ki, double kd)
{
    unsigned char cmd[] = {INITIALIZE_MOTOR_CONTROLLER, motor_index, kp, ki, kd};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// SET_MOTOR_TARGET_VELOCITY: This command sets the target velocity for the specified motor.
void KinisiController::set_motor_target_velocity(uint8_t motor_index, uint8_t direction, uint16_t speed)
{
    unsigned char cmd[] = {SET_MOTOR_TARGET_VELOCITY, motor_index, direction, speed};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// DELETE_MOTOR_CONTROLLER: This command deletes the controller for the specified motor.
void KinisiController::delete_motor_controller(uint8_t motor_index)
{
    unsigned char cmd[] = {DELETE_MOTOR_CONTROLLER, motor_index};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// INITIALIZE_ENCODER: This command initializes an encoder and prepares it for use.
void KinisiController::initialize_encoder(uint8_t encoder_index)
{
    unsigned char cmd[] = {INITIALIZE_ENCODER, encoder_index};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// GET_ENCODER_VALUE: This command retrieves the current value of the encoder.
void KinisiController::get_encoder_value(uint8_t encoder_index)
{
    unsigned char cmd[] = {GET_ENCODER_VALUE, encoder_index};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// INITIALIZE_GPIO_PIN: This command initializes a digital pin and prepares it for use.
void KinisiController::initialize_gpio_pin(uint8_t pin_number, uint8_t mode)
{
    unsigned char cmd[] = {INITIALIZE_GPIO_PIN, pin_number, mode};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// SET_GPIO_PIN_STATE: This command sets the specified pin to a state.
void KinisiController::set_gpio_pin_state(uint8_t pin_number, uint8_t state)
{
    unsigned char cmd[] = {SET_GPIO_PIN_STATE, pin_number, state};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// GET_GPIO_PIN_STATE: This command gets the state of the specified pin.
void KinisiController::get_gpio_pin_state(uint8_t pin_number)
{
    unsigned char cmd[] = {GET_GPIO_PIN_STATE, pin_number};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// TOGGLE_GPIO_PIN_STATE: This command toggles the specified pin.
void KinisiController::toggle_gpio_pin_state(uint8_t pin_number)
{
    unsigned char cmd[] = {TOGGLE_GPIO_PIN_STATE, pin_number};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// SET_STATUS_LED_STATE: This command sets the status LED to a state.
void KinisiController::set_status_led_state(uint8_t state)
{
    unsigned char cmd[] = {SET_STATUS_LED_STATE, state};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// TOGGLE_STATUS_LED_STATE: This command toggles the status LED.
void KinisiController::toggle_status_led_state()
{
    unsigned char cmd[] = {TOGGLE_STATUS_LED_STATE};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// INITIALIZE_PLATFORM: This command initializes the platform and prepares it for use.
void KinisiController::initialize_platform()
{
    unsigned char cmd[] = {INITIALIZE_PLATFORM};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// SET_PLATFORM_VELOCITY_INPUT: This command sets the velocity input for the platform.
void KinisiController::set_platform_velocity_input(int8_t x, int8_t y, int8_t t)
{
    unsigned char cmd[] = {SET_PLATFORM_VELOCITY_INPUT, x, y, t};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

// SET_PLATFORM_CONTROLLER: This command sets the controller for the platform.
void KinisiController::set_platform_controller()
{
    unsigned char cmd[] = {SET_PLATFORM_CONTROLLER};
    Wire.beginTransmission(this->address);
    Wire.write(sizeof(cmd));
    Wire.endTransmission();

    Wire.beginTransmission(this->address);
    Wire.write(cmd, sizeof(cmd));
    Wire.endTransmission();
}

