// ----------------------------------------------------------------------------
// Kinisi motr controller commands.
// This file is auto generated by the commands generator from JSON file.
// Do not edit this file manually.
// Timestamp: 2026-07-19 23:51:00
// Version: 1.1.0
// ----------------------------------------------------------------------------

#ifndef KINISI_H
#define KINISI_H

#include "Arduino.h"
#include "i2cutils.h"

// Commands// This command initializes a motor and prepares it for use.
#define INITIALIZE_MOTOR 0x01

// This command sets the speed of the specified motor in PWM.
#define SET_MOTOR_SPEED 0x02

// This command stops motor by setting its speed to 0.
#define STOP_MOTOR 0x03

// This command brakes motor.
#define BRAKE_MOTOR 0x04

// This command sets the controller for the specified motor.
#define INITIALIZE_MOTOR_CONTROLLER 0x05

// This command sets the target speed for the specified motor in radians.
#define SET_MOTOR_TARGET_SPEED 0x06

// This command resets the controller for the specified motor.
#define RESET_MOTOR_CONTROLLER 0x07

// This command gets the state of the controller for the specified motor.
#define GET_MOTOR_CONTROLLER_STATE 0x08

// This command deletes the controller for the specified motor.
#define DELETE_MOTOR_CONTROLLER 0x09

// This command initializes an encoder and prepares it for use.
#define INITIALIZE_ENCODER 0x11

// This command retrieves the current value of the encoder.
#define GET_ENCODER_VALUE 0x12

// This command starts the odometry calculation for the specified encoder.
#define START_ENCODER_ODOMETRY 0x13

// This command resets the odometry calculation for the specified encoder.
#define RESET_ENCODER_ODOMETRY 0x14

// This command stops the odometry calculation for the specified encoder.
#define STOP_ENCODER_ODOMETRY 0x15

// This command retrieves the odometry of the specified encoder.
#define GET_ENCODER_ODOMETRY 0x16

// This command initializes a digital pin and prepares it for use.
#define INITIALIZE_GPIO_PIN 0x20

// This command sets the specified pin to a state.
#define SET_GPIO_PIN_STATE 0x21

// This command gets the state of the specified pin.
#define GET_GPIO_PIN_STATE 0x22

// This command toggles the specified pin.
#define TOGGLE_GPIO_PIN_STATE 0x23

// This command sets the status LED to a state.
#define SET_STATUS_LED_STATE 0x25

// This command toggles the status LED.
#define TOGGLE_STATUS_LED_STATE 0x26

// This command initializes a mecanum platform and prepares it for use.
#define INITIALIZE_MECANUM_PLATFORM 0x30

// This command initializes a omni platform and prepares it for use.
#define INITIALIZE_OMNI_PLATFORM 0x31

// This command initializes a differential platform and prepares it for use.
#define INITIALIZE_DIFFERENTIAL_PLATFORM 0x32

// This command sets the velocity for the platform in PWM.
#define SET_PLATFORM_VELOCITY 0x40

// This command sets the controller for the platform.
#define START_PLATFORM_CONTROLLER 0x41

// This command set the target velocity for the platform in meters per second.
#define SET_PLATFORM_TARGET_VELOCITY 0x42

// This command gets the current velocity of the platform in meters per second.
#define GET_PLATFORM_CURRENT_VELOCITY 0x43

// This command stops the controller for the platform.
#define STOP_PLATFORM_CONTROLLER 0x44

// This command starts the odometry calculation for the platform.
#define START_PLATFORM_ODOMETRY 0x45

// This command resets the odometry calculation for the platform.
#define RESET_PLATFORM_ODOMETRY 0x46

// This command stops the odometry calculation for the platform.
#define STOP_PLATFORM_ODOMETRY 0x47

// This command retrieves the odometry of the platform in meters and radians.
#define GET_PLATFORM_ODOMETRY 0x48


class KinisiController
{
public:
    // Constructor
    KinisiController(int address);

    // Starts Wire library
    void begin();

    // INITIALIZE_MOTOR: This command initializes a motor and prepares it for use.
    void initialize_motor(uint8_t motor_index, bool is_reversed);

    // SET_MOTOR_SPEED: This command sets the speed of the specified motor in PWM.
    void set_motor_speed(uint8_t motor_index, double pwm);

    // STOP_MOTOR: This command stops motor by setting its speed to 0.
    void stop_motor(uint8_t motor_index);

    // BRAKE_MOTOR: This command brakes motor.
    void brake_motor(uint8_t motor_index);

    // INITIALIZE_MOTOR_CONTROLLER: This command sets the controller for the specified motor.
    void initialize_motor_controller(uint8_t motor_index, bool is_reversed, uint8_t encoder_index, bool is_encoder_reversed, double encoder_resolution, double kp, double ki, double kd, double integral_limit);

    // SET_MOTOR_TARGET_SPEED: This command sets the target speed for the specified motor in radians.
    void set_motor_target_speed(uint8_t motor_index, double speed);

    // RESET_MOTOR_CONTROLLER: This command resets the controller for the specified motor.
    void reset_motor_controller(uint8_t motor_index);

    // GET_MOTOR_CONTROLLER_STATE: This command gets the state of the controller for the specified motor.
    object get_motor_controller_state(uint8_t motor_index);

    // DELETE_MOTOR_CONTROLLER: This command deletes the controller for the specified motor.
    void delete_motor_controller(uint8_t motor_index);

    // INITIALIZE_ENCODER: This command initializes an encoder and prepares it for use.
    void initialize_encoder(uint8_t encoder_index, double encoder_resolution, bool is_reversed);

    // GET_ENCODER_VALUE: This command retrieves the current value of the encoder.
    uint16_t get_encoder_value(uint8_t encoder_index);

    // START_ENCODER_ODOMETRY: This command starts the odometry calculation for the specified encoder.
    void start_encoder_odometry(uint8_t encoder_index);

    // RESET_ENCODER_ODOMETRY: This command resets the odometry calculation for the specified encoder.
    void reset_encoder_odometry(uint8_t encoder_index);

    // STOP_ENCODER_ODOMETRY: This command stops the odometry calculation for the specified encoder.
    void stop_encoder_odometry(uint8_t encoder_index);

    // GET_ENCODER_ODOMETRY: This command retrieves the odometry of the specified encoder.
    double get_encoder_odometry(uint8_t encoder_index);

    // INITIALIZE_GPIO_PIN: This command initializes a digital pin and prepares it for use.
    void initialize_gpio_pin(uint8_t pin_number, uint8_t mode);

    // SET_GPIO_PIN_STATE: This command sets the specified pin to a state.
    void set_gpio_pin_state(uint8_t pin_number, uint8_t state);

    // GET_GPIO_PIN_STATE: This command gets the state of the specified pin.
    uint8_t get_gpio_pin_state(uint8_t pin_number);

    // TOGGLE_GPIO_PIN_STATE: This command toggles the specified pin.
    void toggle_gpio_pin_state(uint8_t pin_number);

    // SET_STATUS_LED_STATE: This command sets the status LED to a state.
    void set_status_led_state(uint8_t state);

    // TOGGLE_STATUS_LED_STATE: This command toggles the status LED.
    void toggle_status_led_state();

    // INITIALIZE_MECANUM_PLATFORM: This command initializes a mecanum platform and prepares it for use.
    void initialize_mecanum_platform(bool is_reversed_0, bool is_reversed_1, bool is_reversed_2, bool is_reversed_3, bool is_encoder_reversed_0, bool is_encoder_reversed_1, bool is_encoder_reversed_2, bool is_encoder_reversed_3, double length, double width, double wheels_diameter, double encoder_resolution);

    // INITIALIZE_OMNI_PLATFORM: This command initializes a omni platform and prepares it for use.
    void initialize_omni_platform(bool is_reversed_0, bool is_reversed_1, bool is_reversed_2, bool is_encoder_reversed_0, bool is_encoder_reversed_1, bool is_encoder_reversed_2, double wheels_diameter, double robot_radius, double encoder_resolution);

    // INITIALIZE_DIFFERENTIAL_PLATFORM: This command initializes a differential platform and prepares it for use.
    void initialize_differential_platform(bool is_reversed_0, bool is_reversed_1, bool is_encoder_reversed_0, bool is_encoder_reversed_1, double wheel_diameter, double wheel_base, double encoder_resolution);

    // SET_PLATFORM_VELOCITY: This command sets the velocity for the platform in PWM.
    void set_platform_velocity(double x, double y, double t);

    // START_PLATFORM_CONTROLLER: This command sets the controller for the platform.
    void start_platform_controller(double kp, double ki, double kd, double integral_limit);

    // SET_PLATFORM_TARGET_VELOCITY: This command set the target velocity for the platform in meters per second.
    void set_platform_target_velocity(double x, double y, double t);

    // GET_PLATFORM_CURRENT_VELOCITY: This command gets the current velocity of the platform in meters per second.
    object get_platform_current_velocity();

    // STOP_PLATFORM_CONTROLLER: This command stops the controller for the platform.
    void stop_platform_controller();

    // START_PLATFORM_ODOMETRY: This command starts the odometry calculation for the platform.
    void start_platform_odometry();

    // RESET_PLATFORM_ODOMETRY: This command resets the odometry calculation for the platform.
    void reset_platform_odometry();

    // STOP_PLATFORM_ODOMETRY: This command stops the odometry calculation for the platform.
    void stop_platform_odometry();

    // GET_PLATFORM_ODOMETRY: This command retrieves the odometry of the platform in meters and radians.
    object get_platform_odometry();

private:
    uint8_t address;
};

#endif // KINISI_H
