// ----------------------------------------------------------------------------
// Kinisi motr controller commands.
// This file is auto generated by the commands generator from JSON file.
// Do not edit this file manually.
// Timestamp: 2026-07-30 22:56:00
// Version: 1.4.0
// ----------------------------------------------------------------------------

#ifndef KINISI_H
#define KINISI_H

#include "Arduino.h"
#include "i2cutils.h"

// Commands// This command initializes a motor and prepares it for use. Ignored if the motor is currently owned by an active platform (one of its wheels), so platform wheels are not reconfigured out from under the platform.
#define INITIALIZE_MOTOR 0x01

// This command sets the speed of the specified motor in PWM. Ignored if the motor is currently owned by an active platform (one of its wheels); use the platform velocity commands to drive platform wheels.
#define SET_MOTOR_SPEED 0x02

// Coasts the motor to a stop: both H-bridge outputs are driven low, leaving the motor terminals open (high impedance) so it free-wheels and spins down gradually under its own friction. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to stop a platform, use STOP_PLATFORM_CONTROLLER, COAST_PLATFORM or BRAKE_PLATFORM instead. Use STOP_MOTOR for a soft, low-stress stop; use BRAKE_MOTOR when you need the motor to hold position and stop quickly.
#define STOP_MOTOR 0x03

// Actively brakes the motor (short brake): both H-bridge outputs are driven high, shorting the motor terminals together so the motor's own back-EMF resists rotation and it stops quickly and holds position. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to brake a platform, use BRAKE_PLATFORM (or STOP_PLATFORM_CONTROLLER / COAST_PLATFORM) instead. Use BRAKE_MOTOR for a fast, holding stop; use STOP_MOTOR to let the motor coast freely instead.
#define BRAKE_MOTOR 0x04

// This command sets the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels), so it cannot create a competing controller on a platform wheel.
#define INITIALIZE_MOTOR_CONTROLLER 0x05

// This command sets the target speed for the specified motor in radians. Ignored if the motor is currently owned by an active platform (one of its wheels); use SET_PLATFORM_TARGET_VELOCITY to drive platform wheels.
#define SET_MOTOR_TARGET_SPEED 0x06

// This command resets the closed-loop controller for the specified motor: it clears the accumulated PID state (integrator windup, derivative history and internal output) and re-zeros the target speed, while keeping the controller running with its existing tuning (kp/ki/kd). Use it to recover from integrator windup or to bring a motor cleanly to a stop without deleting and re-initializing the controller. No effect if no controller is running for that motor, and ignored if the motor is currently owned by an active platform (one of its wheels).
#define RESET_MOTOR_CONTROLLER 0x07

// This command gets the state of the controller for the specified motor.
#define GET_MOTOR_CONTROLLER_STATE 0x08

// This command deletes the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels); use STOP_PLATFORM_CONTROLLER to stop the platform controller instead.
#define DELETE_MOTOR_CONTROLLER 0x09

// This command sets the global update frequency (in Hz) of the closed-loop motor controller task. All motor controllers share a single control loop, so this frequency is global and affects every currently running controller as well as any created afterwards; the PID sampling time is updated to match. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 10 Hz (100 ms) at start-up.
#define SET_CONTROLLER_FREQUENCY 0x0A

// This command retrieves the current global update frequency (in Hz) of the closed-loop motor controller task.
#define GET_CONTROLLER_FREQUENCY 0x0B

// This command initializes an encoder and prepares it for use.
#define INITIALIZE_ENCODER 0x11

// This command retrieves the current value of the encoder.
#define GET_ENCODER_VALUE 0x12

// This command starts the odometry calculation for the specified encoder.
#define START_ENCODER_ODOMETRY 0x13

// This command resets the odometry calculation for the specified encoder.
#define RESET_ENCODER_ODOMETRY 0x14

// This command stops the odometry calculation for the specified encoder.
#define STOP_ENCODER_ODOMETRY 0x15

// This command retrieves the odometry of the specified encoder.
#define GET_ENCODER_ODOMETRY 0x16

// This command sets the global update frequency (in Hz) of the odometry task. A single odometry task integrates all encoder and platform odometry, so this frequency is global. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 20 Hz (50 ms) at start-up.
#define SET_ODOMETRY_FREQUENCY 0x17

// This command retrieves the current global update frequency (in Hz) of the odometry task.
#define GET_ODOMETRY_FREQUENCY 0x18

// This command initializes a digital pin and prepares it for use.
#define INITIALIZE_GPIO_PIN 0x20

// This command sets the specified pin to a state.
#define SET_GPIO_PIN_STATE 0x21

// This command gets the state of the specified pin.
#define GET_GPIO_PIN_STATE 0x22

// This command toggles the specified pin.
#define TOGGLE_GPIO_PIN_STATE 0x23

// This command sets the status LED to a state.
#define SET_STATUS_LED_STATE 0x25

// This command toggles the status LED.
#define TOGGLE_STATUS_LED_STATE 0x26

// This command initializes a mecanum (4-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1, 2 and 3 (one per wheel), which correspond to the is_reversed_0..3 and is_encoder_reversed_0..3 parameters. All four motor slots are occupied by this platform.
#define INITIALIZE_MECANUM_PLATFORM 0x30

// This command initializes an omni (3-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1 and 2 (one per wheel), which correspond to the is_reversed_0..2 and is_encoder_reversed_0..2 parameters. Motor index 3 is not used by this platform and stays free for other purposes.
#define INITIALIZE_OMNI_PLATFORM 0x31

// This command initializes a differential (2-wheel) platform and prepares it for use. It uses motor and encoder index 0 for the left wheel and index 1 for the right wheel, which correspond to the is_reversed_0/1 and is_encoder_reversed_0/1 parameters. Motor indices 2 and 3 are not used by this platform and stay free for other purposes.
#define INITIALIZE_DIFFERENTIAL_PLATFORM 0x32

// This command sets the velocity for the platform in PWM.
#define SET_PLATFORM_VELOCITY 0x40

// This command sets the controller for the platform.
#define START_PLATFORM_CONTROLLER 0x41

// This command set the target velocity for the platform in meters per second.
#define SET_PLATFORM_TARGET_VELOCITY 0x42

// This command gets the current velocity of the platform in meters per second.
#define GET_PLATFORM_CURRENT_VELOCITY 0x43

// This command stops the controller for the platform.
#define STOP_PLATFORM_CONTROLLER 0x44

// This command starts the odometry calculation for the platform.
#define START_PLATFORM_ODOMETRY 0x45

// This command resets the odometry calculation for the platform.
#define RESET_PLATFORM_ODOMETRY 0x46

// This command stops the odometry calculation for the platform.
#define STOP_PLATFORM_ODOMETRY 0x47

// This command retrieves the odometry of the platform in meters and radians.
#define GET_PLATFORM_ODOMETRY 0x48

// This command actively brakes all of this platform's wheel motors (short brake) so they resist motion and hold position, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors resist motion until a new command is issued.
#define BRAKE_PLATFORM 0x49

// This command lets all of this platform's wheel motors coast freely (high impedance) so they spin down without resistance, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors spin down without resistance.
#define COAST_PLATFORM 0x4A


class KinisiController
{
public:
    // Constructor
    KinisiController(int address);

    // Starts Wire library
    void begin();

    // INITIALIZE_MOTOR: This command initializes a motor and prepares it for use. Ignored if the motor is currently owned by an active platform (one of its wheels), so platform wheels are not reconfigured out from under the platform.
    void initialize_motor(uint8_t motor_index, bool is_reversed);

    // SET_MOTOR_SPEED: This command sets the speed of the specified motor in PWM. Ignored if the motor is currently owned by an active platform (one of its wheels); use the platform velocity commands to drive platform wheels.
    void set_motor_speed(uint8_t motor_index, double pwm);

    // STOP_MOTOR: Coasts the motor to a stop: both H-bridge outputs are driven low, leaving the motor terminals open (high impedance) so it free-wheels and spins down gradually under its own friction. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to stop a platform, use STOP_PLATFORM_CONTROLLER, COAST_PLATFORM or BRAKE_PLATFORM instead. Use STOP_MOTOR for a soft, low-stress stop; use BRAKE_MOTOR when you need the motor to hold position and stop quickly.
    void stop_motor(uint8_t motor_index);

    // BRAKE_MOTOR: Actively brakes the motor (short brake): both H-bridge outputs are driven high, shorting the motor terminals together so the motor's own back-EMF resists rotation and it stops quickly and holds position. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to brake a platform, use BRAKE_PLATFORM (or STOP_PLATFORM_CONTROLLER / COAST_PLATFORM) instead. Use BRAKE_MOTOR for a fast, holding stop; use STOP_MOTOR to let the motor coast freely instead.
    void brake_motor(uint8_t motor_index);

    // INITIALIZE_MOTOR_CONTROLLER: This command sets the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels), so it cannot create a competing controller on a platform wheel.
    void initialize_motor_controller(uint8_t motor_index, bool is_reversed, uint8_t encoder_index, bool is_encoder_reversed, double encoder_resolution, double kp, double ki, double kd, double integral_limit);

    // SET_MOTOR_TARGET_SPEED: This command sets the target speed for the specified motor in radians. Ignored if the motor is currently owned by an active platform (one of its wheels); use SET_PLATFORM_TARGET_VELOCITY to drive platform wheels.
    void set_motor_target_speed(uint8_t motor_index, double speed);

    // RESET_MOTOR_CONTROLLER: This command resets the closed-loop controller for the specified motor: it clears the accumulated PID state (integrator windup, derivative history and internal output) and re-zeros the target speed, while keeping the controller running with its existing tuning (kp/ki/kd). Use it to recover from integrator windup or to bring a motor cleanly to a stop without deleting and re-initializing the controller. No effect if no controller is running for that motor, and ignored if the motor is currently owned by an active platform (one of its wheels).
    void reset_motor_controller(uint8_t motor_index);

    // GET_MOTOR_CONTROLLER_STATE: This command gets the state of the controller for the specified motor.
    object get_motor_controller_state(uint8_t motor_index);

    // DELETE_MOTOR_CONTROLLER: This command deletes the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels); use STOP_PLATFORM_CONTROLLER to stop the platform controller instead.
    void delete_motor_controller(uint8_t motor_index);

    // SET_CONTROLLER_FREQUENCY: This command sets the global update frequency (in Hz) of the closed-loop motor controller task. All motor controllers share a single control loop, so this frequency is global and affects every currently running controller as well as any created afterwards; the PID sampling time is updated to match. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 10 Hz (100 ms) at start-up.
    void set_controller_frequency(uint16_t frequency);

    // GET_CONTROLLER_FREQUENCY: This command retrieves the current global update frequency (in Hz) of the closed-loop motor controller task.
    uint16_t get_controller_frequency();

    // INITIALIZE_ENCODER: This command initializes an encoder and prepares it for use.
    void initialize_encoder(uint8_t encoder_index, double encoder_resolution, bool is_reversed);

    // GET_ENCODER_VALUE: This command retrieves the current value of the encoder.
    uint16_t get_encoder_value(uint8_t encoder_index);

    // START_ENCODER_ODOMETRY: This command starts the odometry calculation for the specified encoder.
    void start_encoder_odometry(uint8_t encoder_index);

    // RESET_ENCODER_ODOMETRY: This command resets the odometry calculation for the specified encoder.
    void reset_encoder_odometry(uint8_t encoder_index);

    // STOP_ENCODER_ODOMETRY: This command stops the odometry calculation for the specified encoder.
    void stop_encoder_odometry(uint8_t encoder_index);

    // GET_ENCODER_ODOMETRY: This command retrieves the odometry of the specified encoder.
    double get_encoder_odometry(uint8_t encoder_index);

    // SET_ODOMETRY_FREQUENCY: This command sets the global update frequency (in Hz) of the odometry task. A single odometry task integrates all encoder and platform odometry, so this frequency is global. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 20 Hz (50 ms) at start-up.
    void set_odometry_frequency(uint16_t frequency);

    // GET_ODOMETRY_FREQUENCY: This command retrieves the current global update frequency (in Hz) of the odometry task.
    uint16_t get_odometry_frequency();

    // INITIALIZE_GPIO_PIN: This command initializes a digital pin and prepares it for use.
    void initialize_gpio_pin(uint8_t pin_number, uint8_t mode);

    // SET_GPIO_PIN_STATE: This command sets the specified pin to a state.
    void set_gpio_pin_state(uint8_t pin_number, uint8_t state);

    // GET_GPIO_PIN_STATE: This command gets the state of the specified pin.
    uint8_t get_gpio_pin_state(uint8_t pin_number);

    // TOGGLE_GPIO_PIN_STATE: This command toggles the specified pin.
    void toggle_gpio_pin_state(uint8_t pin_number);

    // SET_STATUS_LED_STATE: This command sets the status LED to a state.
    void set_status_led_state(uint8_t state);

    // TOGGLE_STATUS_LED_STATE: This command toggles the status LED.
    void toggle_status_led_state();

    // INITIALIZE_MECANUM_PLATFORM: This command initializes a mecanum (4-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1, 2 and 3 (one per wheel), which correspond to the is_reversed_0..3 and is_encoder_reversed_0..3 parameters. All four motor slots are occupied by this platform.
    void initialize_mecanum_platform(bool is_reversed_0, bool is_reversed_1, bool is_reversed_2, bool is_reversed_3, bool is_encoder_reversed_0, bool is_encoder_reversed_1, bool is_encoder_reversed_2, bool is_encoder_reversed_3, double length, double width, double wheels_diameter, double encoder_resolution);

    // INITIALIZE_OMNI_PLATFORM: This command initializes an omni (3-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1 and 2 (one per wheel), which correspond to the is_reversed_0..2 and is_encoder_reversed_0..2 parameters. Motor index 3 is not used by this platform and stays free for other purposes.
    void initialize_omni_platform(bool is_reversed_0, bool is_reversed_1, bool is_reversed_2, bool is_encoder_reversed_0, bool is_encoder_reversed_1, bool is_encoder_reversed_2, double wheels_diameter, double robot_radius, double encoder_resolution);

    // INITIALIZE_DIFFERENTIAL_PLATFORM: This command initializes a differential (2-wheel) platform and prepares it for use. It uses motor and encoder index 0 for the left wheel and index 1 for the right wheel, which correspond to the is_reversed_0/1 and is_encoder_reversed_0/1 parameters. Motor indices 2 and 3 are not used by this platform and stay free for other purposes.
    void initialize_differential_platform(bool is_reversed_0, bool is_reversed_1, bool is_encoder_reversed_0, bool is_encoder_reversed_1, double wheel_diameter, double wheel_base, double encoder_resolution);

    // SET_PLATFORM_VELOCITY: This command sets the velocity for the platform in PWM.
    void set_platform_velocity(double x, double y, double t);

    // START_PLATFORM_CONTROLLER: This command sets the controller for the platform.
    void start_platform_controller(double kp, double ki, double kd, double integral_limit);

    // SET_PLATFORM_TARGET_VELOCITY: This command set the target velocity for the platform in meters per second.
    void set_platform_target_velocity(double x, double y, double t);

    // GET_PLATFORM_CURRENT_VELOCITY: This command gets the current velocity of the platform in meters per second.
    object get_platform_current_velocity();

    // STOP_PLATFORM_CONTROLLER: This command stops the controller for the platform.
    void stop_platform_controller();

    // START_PLATFORM_ODOMETRY: This command starts the odometry calculation for the platform.
    void start_platform_odometry();

    // RESET_PLATFORM_ODOMETRY: This command resets the odometry calculation for the platform.
    void reset_platform_odometry();

    // STOP_PLATFORM_ODOMETRY: This command stops the odometry calculation for the platform.
    void stop_platform_odometry();

    // GET_PLATFORM_ODOMETRY: This command retrieves the odometry of the platform in meters and radians.
    object get_platform_odometry();

    // BRAKE_PLATFORM: This command actively brakes all of this platform's wheel motors (short brake) so they resist motion and hold position, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors resist motion until a new command is issued.
    void brake_platform();

    // COAST_PLATFORM: This command lets all of this platform's wheel motors coast freely (high impedance) so they spin down without resistance, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors spin down without resistance.
    void coast_platform();

private:
    uint8_t address;
};

#endif // KINISI_H
